name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
